export type Product = {
    accessories: { sku: number };
    color: string;
    condition: string;
    customerReviewAverage: number;
    customerReviewCount: number;
    customerTopRated: number;
    depth: string;
    description: string;
    details: { name: string; value: string };
    digital: boolean;
    features: { feature: string }[];
    format: string;
    height: string;
    includedItemList: { includedItem: string }[];
    longDescription: string;
    longDescriptionHtml: string;
    manufacturer: string;
    modelNumber: string;
    name: string;
    preowned: boolean;
    productVariations: { sku: number }[];
    quantityLimit: number;
    releaseDate: Date;
    shortDescription: string;
    shortDescriptionHtml: string;
    sku: number;
    upc: string;
    warrantyLabor: string;
    warrantyParts: string;
    weight: string;
    width: string;
};
